name: "Build"

on:
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubicloud-standard-16
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    # Unnecessary - GH official Ubuntu image already has these up-to-date
    # - name: Install pre-reqs
    #   run : |
    #     sudo apt update && sudo apt install curl python3 python3-pip git

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Download Betterfox latest release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir betterfox
        cd betterfox
        set ver $(gh release list -R yokoffing/Betterfox --exclude-pre-releases -L 1 --json tagName | jq -r .[0].tagName)
        gh release download -R yokoffing/Betterfox $ver --archive=tar.gz -O betterfox.tar.gz
        tar -xf betterfox.tar.gz --strip-components=1

    - name: Get Version
      run: | 
        VERSION=$(curl https://whattrainisitnow.com/api/firefox/releases/ | jq -r 'to_entries | sort_by(.value) | last | .key')
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
      

    # TODO: This exists to do all the dependency bootstrapping. It's not ideal, but they don't seem to care?
    # https://bugzilla.mozilla.org/show_bug.cgi?id=1740139
    # https://bugzilla.mozilla.org/show_bug.cgi?id=1759544
    - name: Download Firefox source
      run: |
        curl -LO https://raw.githubusercontent.com/mozilla-firefox/firefox/refs/heads/main/python/mozboot/bin/bootstrap.py
        python3 bootstrap.py --no-interactive --application-choice 'Firefox for Desktop'
        cd firefox
        git fetch origin --tags
        git checkout FIREFOX_${VERSION//./_}_RELEASE
    
    - name: Download Firefox latest stable source and bootstrap
      run: |
        mv firefox firefox-nightly
        mkdir firefox
        cd firefox
        TARBALL_URL="https://archive.mozilla.org/pub/firefox/releases/${VERSION}/source/firefox-${VERSION}.source.tar.xz"
        curl -L -o firefox-source.tar.xz ${TARBALL_URL}
        tar -xf firefox-source.tar.xz --strip-components=1
        ls -latr
        ./mach bootstrap --application-choice "Firefox for Desktop"
      

    - name: Add mozconfig from repo
      run: |
        cp ${GITHUB_WORKSPACE}/MozConfigs/Linux64/mozconfig ${GITHUB_WORKSPACE}/firefox/mozconfig

    - name: Apply Betterfox & Custom prefs
      run: |
        cd betterfox
        cp user.js addin.js
        sed -i 's/user_pref/pref/g' addin.js
        cat addin.js >> ../firefox/modules/libpref/init/all.js
        cd ../prefs
        cat additional.js >> ../firefox/modules/libpref/init/all.js

    - name: Build firefox
      run: |
        cd firefox
        ./mach build
        
    - name: Build package
      run: |
        cd firefox
        ./mach package

    - name: Get Package Name
      run: | 
        PACKAGE_PATH=./firefox/objdir-opt/dist/$(cat ./firefox/objdir-opt/dist/package_name.txt)
        mv ${PACKAGE_PATH} ./firefox.tar.gz
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: firefox-build
        path: ./firefox.tar.gz
        retention-days: 5
