name: "Build"

on:
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubicloud-standard-2
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    # Unnecessary - GH official Ubuntu image already has these up-to-date
    # - name: Install pre-reqs
    #   run : |
    #     sudo apt update && sudo apt install curl python3 python3-pip git

    - name: Checkout Repo
      uses: actions/checkout@v4

    # TODO: Replace this with getting tagged source
    # Use the official release train API from https://whattrainisitnow.com/api/firefox/releases/
    # Get the version for the latest date, then replace in this URL
    # https://archive.mozilla.org/pub/firefox/releases/142.0.1/source/firefox-142.0.1.source.tar.xz
    # Also need to figure out what build tooling I would need
    # Looks like I bootstrap via 
    # ./mach bootstrap --no-interactive --application-choice "Firefox for Desktop"
    - name: Download Firefox source
      run: |
        curl -LO https://raw.githubusercontent.com/mozilla-firefox/firefox/refs/heads/main/python/mozboot/bin/bootstrap.py
        python3 bootstrap.py --no-interactive --application-choice 'Firefox for Desktop'
        cd firefox
        git pull
        ls -latr

    # - name: Add mozconfig from repo

    - name: Build firefox
      run: |
        cd firefox
        ./mach build
