name: "Build"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    # Unnecessary - GH official Ubuntu image already has these up-to-date
    # - name: Install pre-reqs
    #   run : |
    #     sudo apt update && sudo apt install curl python3 python3-pip git

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Download Firefox source
      run: |
        curl -LO https://raw.githubusercontent.com/mozilla-firefox/firefox/refs/heads/main/python/mozboot/bin/bootstrap.py
        python3 bootstrap.py --no-interactive --application-choice Firefox for Desktop
        cd firefox
        git pull
        ls -latr

    # - name: Add mozconfig from repo

    - name: Build firefox
      run: |
        cd firefox
        ./mach build
